/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_BIOCHEM_SCHEMA_PB_H_INCLUDED
#define PB_BIOCHEM_SCHEMA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Mobile -> ESP32: RPC Handshake */
typedef struct _DeviceIntent {
    uint32_t request_id;
    char target_operation[64]; /* e.g., "START_ACQUISITION" */
} DeviceIntent;

/* ESP32 -> Mobile: Continuous 10Hz Telemetry */
typedef struct _SpectralTelemetry {
    uint32_t timestamp_ms;
    uint32_t sequence_number;
    /* 14 channels: F1-F8, FZ, FY, FX, NIR, Clear, Flicker */
    pb_size_t spectral_channels_count;
    uint32_t spectral_channels[14];
    float ambient_temperature_c;
} SpectralTelemetry;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define DeviceIntent_init_default                {0, ""}
#define SpectralTelemetry_init_default           {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define DeviceIntent_init_zero                   {0, ""}
#define SpectralTelemetry_init_zero              {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceIntent_request_id_tag              1
#define DeviceIntent_target_operation_tag        2
#define SpectralTelemetry_timestamp_ms_tag       1
#define SpectralTelemetry_sequence_number_tag    2
#define SpectralTelemetry_spectral_channels_tag  3
#define SpectralTelemetry_ambient_temperature_c_tag 4


/* Struct field encoding specification for nanopb */
#define DeviceIntent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   SINGULAR, STRING,   target_operation,   2)
#define DeviceIntent_CALLBACK NULL
#define DeviceIntent_DEFAULT NULL

#define SpectralTelemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_number,   2) \
X(a, STATIC,   REPEATED, UINT32,   spectral_channels,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    ambient_temperature_c, 4)
#define SpectralTelemetry_CALLBACK NULL
#define SpectralTelemetry_DEFAULT NULL

extern const pb_msgdesc_t DeviceIntent_msg;
extern const pb_msgdesc_t SpectralTelemetry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DeviceIntent_fields &DeviceIntent_msg
#define SpectralTelemetry_fields &SpectralTelemetry_msg

/* Maximum encoded size of messages (where known) */
#define BIOCHEM_SCHEMA_PB_H_MAX_SIZE             SpectralTelemetry_size
#define DeviceIntent_size                        71
#define SpectralTelemetry_size                   96

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
